// Code generated by mockery v2.12.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	commands "github.com/zmoog/classeviva/commands"

	testing "testing"
)

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

// ExecuteWith provides a mock function with given fields: uow
func (_m *Command) ExecuteWith(uow commands.UnitOfWork) error {
	ret := _m.Called(uow)

	var r0 error
	if rf, ok := ret.Get(0).(func(commands.UnitOfWork) error); ok {
		r0 = rf(uow)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCommand creates a new instance of Command. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewCommand(t testing.TB) *Command {
	mock := &Command{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
