// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	spaggiari "github.com/zmoog/classeviva/adapters/spaggiari"
)

// NoticeboardsReceiver is an autogenerated mock type for the NoticeboardsReceiver type
type NoticeboardsReceiver struct {
	mock.Mock
}

// List provides a mock function with given fields:
func (_m *NoticeboardsReceiver) List() ([]spaggiari.Noticeboard, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []spaggiari.Noticeboard
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]spaggiari.Noticeboard, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []spaggiari.Noticeboard); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]spaggiari.Noticeboard)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewNoticeboardsReceiver creates a new instance of NoticeboardsReceiver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoticeboardsReceiver(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoticeboardsReceiver {
	mock := &NoticeboardsReceiver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
