name: OpenAPI Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'openapi.yaml'
      - '.github/workflows/openapi-docs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Generate HTML documentation
        run: |
          # Install Redoc CLI
          npm install -g @redocly/cli
          
          # Create output directory
          mkdir -p docs
          
          # Generate standalone HTML file
          redocly build-docs openapi.yaml --output docs/index.html
          
          # Create a simple redirect page at root
          cat > docs/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <title>Redirecting...</title>
            <meta http-equiv="refresh" content="0; url=/classeviva/">
          </head>
          <body>
            Redirecting to documentation...
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
